FROM apache/airflow:2.7.1
#RUN pip install -U pip --upgrade pip
# RUN pip install pipenv

# Copy requirements file to container
COPY requirements.txt /requirements.txt

# Install python dependencies
RUN pip install --no-cache-dir -r /requirements.txt